# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration_account.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrAccounts(object):
    def setupUi(self, RegistrAccounts):
        RegistrAccounts.setObjectName("RegistrAccounts")
        RegistrAccounts.resize(472, 531)
        self.gridLayout_3 = QtWidgets.QGridLayout(RegistrAccounts)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(RegistrAccounts)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 3)
        self.pushButton = QtWidgets.QPushButton(RegistrAccounts)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(RegistrAccounts)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 3)
        self.spinBox = QtWidgets.QSpinBox(RegistrAccounts)
        self.spinBox.setProperty("value", 3)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(RegistrAccounts)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 2)
        self.spinBox_2 = QtWidgets.QSpinBox(RegistrAccounts)
        self.spinBox_2.setProperty("value", 5)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(RegistrAccounts)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(RegistrAccounts)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(RegistrAccounts)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 3, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(RegistrAccounts)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(RegistrAccounts)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(RegistrAccounts)
        self.commandLinkButton.setIconSize(QtCore.QSize(18, 18))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.gridLayout_3.addWidget(self.commandLinkButton, 2, 0, 1, 1)

        self.retranslateUi(RegistrAccounts)
        QtCore.QMetaObject.connectSlotsByName(RegistrAccounts)

    def retranslateUi(self, RegistrAccounts):
        _translate = QtCore.QCoreApplication.translate
        RegistrAccounts.setWindowTitle(_translate("RegistrAccounts", "Регистрация аккаунтов"))
        self.label_4.setText(_translate("RegistrAccounts", "Файл с информацией для аккаунтов"))
        self.pushButton.setText(_translate("RegistrAccounts", "Выбрать файл"))
        self.label_2.setText(_translate("RegistrAccounts", "Сколько раз повторять задачу"))
        self.label_5.setText(_translate("RegistrAccounts", "Менять ip каждые"))
        self.label_6.setText(_translate("RegistrAccounts", "аккаунтов"))
        self.label_3.setText(_translate("RegistrAccounts", "Логи:"))
        self.pushButton_2.setText(_translate("RegistrAccounts", "Запустить"))
        self.pushButton_3.setText(_translate("RegistrAccounts", "Экстренный выход"))
        self.commandLinkButton.setText(_translate("RegistrAccounts", "Результат задачи"))
